import { utils, writeFile } from 'xlsx';
import { Pokemon } from '../models/pokemon';

export function exportToExcel(pokemons: Pokemon[]) {
  const workbook = utils.book_new();
  const worksheet = utils.json_to_sheet(pokemons);
  utils.book_append_sheet(workbook, worksheet, 'Pokemons');
  writeFile(workbook, 'pokemons.xlsx');
}

export function heavy() {
  return 'dfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfjdfkgdjgdkjgjkdfj'
}